name: CI

on:
    # Trigger workflow only when PR targets master branch
    pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SwiftFormat
      run: brew install swiftformat
    - name: Swift format check
      run: swiftformat . --lint
